### ISSUE TITLE
Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array

### ISSUE THREAD

**Issue by akroii** [pdir/contao-survey#1]
## Bug description
`Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given, called in /home/akroiide/domains/akroii.de/public_html/demo/var/cache/prod/contao/dca/tl_survey_page.php on line 193`

## Steps to reproduce
1. Erstelle eine neue Umfrage
2. Bearbeiten (Stift-Icon)
3. Neue Seite anlegen und "Oben einfügen"

## Expected behavior
Fehlerfreies anlegen einer neuen Seite

## Environment
Contao 4.9.12
pdir/contao-survey dev-master

**Comment by MDevster** [comment]
Fixed by d8bde99 and released as 3.2.8.
