### ISSUE TITLE
participants with German umlauts in exports are shown as FALSCH

### ISSUE THREAD

**Issue by arboc** [pdir/contao-survey#10]
## Bug description
When you have a personal survey (to identify participants) and do a detailed export (raw data) all participant names with a German umlaut are shown as "FALSCH" within the excel sheet

## Steps to reproduce
Do a personal survey for a restriced member group.  
Add a member with a German umlaut (i.e. Müller).   
Fill out the sruvey when you logged in with that member (name with German umlaut).  
Do a detailed export (raw data).  
Open the export with Excel 365 (actual version)  

## Expected behavior
The name of the participant should be shown.  

## Screenshots
![image](https://user-images.githubusercontent.com/4447843/154251801-30a83cb4-df0d-40ff-8ca0-bdba0c643741.png)

## Environment
Contao 4.9  
PHP 7.4

**Comment by cmette** [comment]
## Steps to test is
I have now done the following:
1. created a personal survey for a restricted group of members.
2. logged in as Susanne Müller (test name) and filled out the survey
3. performed a detailed export
4. opened the export *.csv file with MS Excel 2013 and Open Office Calc (Excel 365 is not the best solution :O)

## Result
The name of the participant is displayed as follows

The raw csv looks like this:
```csv
"Frage ID:",5
`Frage#:,1
Sei#.Fra#:,1.1
Fragentyp:,"Offene Frage"
Beantwortet:,1
Übersprungen:,0
Titel:,"Frage 1"
ID,Datum,,"Letzte Seite",Teilnehmer,
19,1,"2022-08-31 06:13:54",2,"Susanne M?ller <susanne.mueller@test.de>","Frage 1"
```
As you can see, the name with German umlauts is no longer exported as FALSE/TRUE, but the umlauts themselves are missing. They are represented by special characters.

If I then import the csv file to Open Office Calc - with the Source File UTF8 option - I get the following file.

![OfficeCalc](https://user-images.githubusercontent.com/13376233/187612530-c2acf348-9816-465f-a56f-d00881f40e89.png)

When I import the csv file to Excel 2013, I get the following file:

![MSExcel2013](https://user-images.githubusercontent.com/13376233/187614360-a8715bcc-6f6b-4e6b-aa10-ffc9d73747d4.png)

## Summary
If this should be the desired result, that everything is OK!

**Comment by arboc** [comment]
ok...  
I see, I forgot to mention, that we are using [phpoffice/phpspreadsheet] (https://packagist.org/packages/phpoffice/phpspreadsheet)  for export.
