### ISSUE TITLE
PR offer: Result page and question categories

### ISSUE THREAD

**Issue by koertho** [pdir/contao-survey#15]
Hi, were currently plan to use this bundle in a project and need two additional features: 

1. Result page: We need to display results direct to the user. My idea is to introduce a new page type where results are displayed, but adjustable from template.
2. Question categories: Have the option to set a category for each question and be able to group the survey result based on this cateogries. Categories are specific to each survey.

I would do PRs for both or just one of the features, if you ok with the features and my implementation ideas. I'm also open for different implementation approaches. 

Additional question: is it ok to raise the php and contao dependency?

**Comment by MDevster** [comment]
You are welcome to make individual PR for both functions. Also raising the dependencies is no problem, we plan to do that for Contao 5 anyway.

**Comment by koertho** [comment]
The category feature need to be discussed before: 

- From my opinion it only makes sense on the multiple choices question type. So I would only add it there.
- To add a category to a answer, my idea was to add a select field behind the answer text field. The input type currently used (textWizard) does not allow such a usage neither one of the other contao widgets. So we need a dependency on a multi column input type like MultiColumnWizard, MultiColumnEditor oder Group Widget. Do you have a preference?

**Comment by MDevster** [comment]
No. 1 - I agree with you there.
No. 2 - We need a bundle that supports Contao 5/PHP 8.1 as soon as possible, because we want to make survey fit for it.  This means to make a PR or to use a bundle where you have it in your own hands.

**Comment by MDevster** [comment]
Group Widget looks good for me 😀
https://github.com/m-vo/contao-group-widget/blob/main/composer.json

**Comment by MDevster** [comment]
MultiColumnEditor should also fit, if you have time 😀

**Comment by koertho** [comment]
I would go for group widget. It's well build and means less work for me :smile:
