### ISSUE TITLE
Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array

### ISSUE THREAD

**Issue by akroii** [pdir/contao-survey#2]
## Bug description
```
Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given, called in /home/xxxxx/domains/xxxxx.de/public_html/demo/var/cache/prod/contao/dca/tl_content.php on line 2935
```

## Steps to reproduce
1. Öffne einen Artikel im Backend
2. Wäre "Umfrage" aus
3. Error appears

## Expected behavior
Inhaltselement mit Einstellungen sind sichtbar im Backend

## Environment
Contao 4.9.12
pdir/contao-survey 3.2.8

**Comment by akroii** [comment]
See PR: [https://github.com/pdir/contao-survey/pull/5](https://github.com/pdir/contao-survey/pull/5)

**Comment by MDevster** [comment]
fixed in version 3.2.9
