### ISSUE TITLE
Lässt sich unter Contao 4.9, 4.13, 5.0 nicht installieren

### ISSUE THREAD

**Issue by AndiMb** [pdir/contao-survey#21]
## Bug description
In einer frische Contao-Installation lässt dich das Plugin nicht installieren. Offenbar werden die Tabellen in der Datenbank nicht angelegt. Dadurch lässt sich auch /contao/install nicht mehr aufrufen.

## Environment
PHP: 7.4
Contao: 4.9, 4.13, 5.0

**Comment by AndiMb** [comment]
Die Ursache liegt offenbar darin, dass die shouldRun Methode von ChoicesFieldMigration.php aufgerufen wird, bevor die Tabellen in der Datenbank angelegt werden. Da die Methode versucht Änderungen an Tabellen einträgen vorzunehmen, führt dies zu einem Fehler im Falle einer Neuinstallation.

**Comment by herrrilke** [comment]
hallo,
das problem besteht mit der "pdir/contao-survey": "^3.4", und C 4.13.14 stand heute immer noch.
gibt es hoffnung auf eine lösung?

**Comment by koertho** [comment]
Hi, workaround wäre `contao:migrate --schema-only` auszuführen

**Comment by MDevster** [comment]
Morgen kommt ein fix

**Comment by herrrilke** [comment]
> Hi, workaround wäre `contao:migrate --schema-only` auszuführen

funktioniert tiptop :)

danke!

**Comment by MDevster** [comment]
Fixed in version3.4.1.
