### ISSUE TITLE
Compatibility with PHP 8

### ISSUE THREAD

**Issue by Total-Reality** [pdir/contao-survey#24]
## Bug description
The extension (3.4.1) is not compatible with PHP 8, because the dependency version is outdated:
[hschottm/contao-textwizard](https://packagist.org/packages/hschottm/contao-textwizard): ^3.2

This is an old version which is not compatible with PHP 8:
https://packagist.org/packages/hschottm/contao-textwizard#3.2.1

## Steps to solve the problem
You need to change the dependency to:
[hschottm/contao-textwizard](https://packagist.org/packages/hschottm/contao-textwizard): ^3.4

**Comment by MDevster** [comment]
I assume that you are using Contao 4.9, right? Text Wizard is no longer available as version 3.4 for Contao 4.9, so if you want to continue using Contao 4.9, you cannot use PHP 8 or higher. If you update to Contao 4.13, you can use PHP 8 or higher again - so the extension is compatible with PHP 8 ;)
We will most likely not consider Contao 4.9 for new features either. Support can be terminated at any time.
See https://contao.org/de/release-plan.html

**Comment by Total-Reality** [comment]
This page uses 4.9, thats right.

What you say makes no sense at all. Most hosters already deactivated PHP 7 in february 2023 or earlier.
It is not useful to suspend so much users, because 4.9 is still the non plus ultra choice atm and it is a supported LTS until Feb. 2024.
4.13 is a still not useful for every project atm.

You force people to delete the extension **or** to have very much trouble, if you have installed more than 10 or 20 extensions e.g. So either you are dealing with an update orgy or you have to change the server/provider...

Btw. I created over 70 extensions and most of them are compatible with Contao 4.4 - 4.13 or compatible with 4.9 - 4.13. You I don't understand the problem.

**Comment by MDevster** [comment]
I understand what your problem is, but unfortunately it's not up to us. Again, the extension or the changes you propose https://packagist.org/packages/hschottm/contao-textwizard#3.4.0 has as dependency Contao 4.13. So the manager would never install version 3.4.0 or 3.4.1 of Contao Texwizard under Contao 4.9. So the developer hschottm decided not to support Contao 4.9 anymore, only he can change this again. Alternatively, you can of course fork the extension and make the change yourself.

**Comment by MDevster** [comment]
There is also an fork from H+H at https://github.com/heimrichhannot/textwizard which you can already use.
