### ISSUE TITLE
Contao Survey Choices Field Migration

### ISSUE THREAD

**Issue by akroii** [pdir/contao-survey#25]
## Bug description
Wenn ich eine multiple Choice Frage anlege und mit Inhalt befülle, möchte er im Installtool (bzw. Contao Manager) eine Migration durchführen die er nicht beenden kann.

## Steps to reproduce
1. Installiere letzte Version
2. Lege ein Survey mit Seiten und Multiple-Choices an
3. Befülle die Multiple-Choices mit Inhalt
4. Geh ins Install-Tool oder führe Datenbankänderungen im Manager aus
5. Fehlermeldung: Contao Survey Choices Field Migration (tritt undendlich auf)

-> Das Resultat ist dann, dass im Group-Widget der choices jeweils ein "Array" als Wort steht.

## Expected behavior
Dazu bin ich zu wenig ein Entwickler. Das Installtool dürfte keine Migration durchführen oder wenn, dann eine erfolgreiche MIgration durchführen und nicht in einer Endlosschleife hängen bleiben.

## Screenshots
![Screenshot 2023-02-16 13520
![Screenshot 2023-02-16 135207](https://user-images.githubusercontent.com/8830861/219371123-01a65e0b-cde9-4c5b-a1eb-4837d9d03b79.png)
7](https://user-images.githubusercontent.com/8830861/219369984-9a90fe8b-515d-4215-a288-2c001cade2ab.png)

## Environment
C4.9.33
pdir/contao-survey 3.4.1

**Comment by cmette** [comment]
hallo @akroii  - ich habe den Fehler behoben - der PR wartet zurzeit auf ein Review - bitte dann mal testen und kurze Rückmeldung geben

**Comment by MDevster** [comment]
Fixed in 3.4.2m, thank you @akroii for the financial support.
