### ISSUE TITLE
Quiz-Möglichkeiten

### ISSUE THREAD

**Issue by akroii** [pdir/contao-survey#3]
## Description
Es wäre toll wenn contao-survey nicht nur Survey macht, sondern auch ein paar Quiz Möglichkeiten bietet. 😉
Bei Multiple-Choice Fragen könnte man z.b. noch richtige und falsche Antworten hinzufügen (Jeweils mit Fehlertext).
Da bräuchte man jedoch dann noch eine Ergebnis-Seite.

**Comment by koertho** [comment]
Wir haben jetzt Ergebnis-Seiten und Antwort-Kategorien, welche du mit Richtig/Falsch belegen kannst, daher ist das hier eventuell für dich schon gelöst :)

**Comment by akroii** [comment]
Oha, muss ich mir anschauen

**Comment by akroii** [comment]
Mit dem was keortho geschrieben hat, Ja! :)

**Comment by seibtph** [comment]
> Wir haben jetzt Ergebnis-Seiten und Antwort-Kategorien, welche du mit Richtig/Falsch belegen kannst, daher ist das hier eventuell für dich schon gelöst :)

Weißt du wie genau das funktioniert mit den Antwort-Kategorien? Ich habe den dev-master installiert und finde aber nichts zu Antwort-Kategorien. Wie kann man definieren welche Antwort die Richtige ist?

**Comment by koertho** [comment]
@seibtph Du kannst an einer Umfrage Kategorien definieren, die können ja auch einfach Richtig/Falsch heißen. Verwenden kannst du sie aber nur in Multiple Choice, zumindest ist das mein letzter Stand. Siehe https://github.com/pdir/contao-survey/pull/17
