### ISSUE TITLE
Feature request: Ajax submit

### ISSUE THREAD

**Issue by koertho** [pdir/contao-survey#37]
## Description
Currently submitting an answer does a complete page reload. We should provide an option to submit answers through ajax. 

Since we need this functionality, I would offer build a PR for this function. I plan it for the first week of may.

**Comment by koertho** [comment]
I'm sorry to say that my colleges figured out a solution that do not need the ajax submit anymore so I can't provide a PR in the next time. I will see if a future project need this functionality or someone other may provide a PR for this functionality.

**Comment by MDevster** [comment]
Thanks for the information, then I'll close the ticket for now.
