### ISSUE TITLE
Question type "Matrixfrage": Using the checkbox "Fragentitel nicht anzeigen" leads to an error

### ISSUE THREAD

**Issue by marcuslelle** [pdir/contao-survey#58]
## Bug description
When using the question type "Matrixfrage" you cannot use the checkbox "Fragentitel nicht anzeigen".

It leads to an error:
request.CRITICAL: Uncaught PHP Exception TypeError: "strlen(): Argument #1 ($string) must be of type string, int given" at /html/contao413/vendor/pdir/contao-survey/src/Resources/contao/forms/FormQuestionWidget.php line 184 {"exception":"[object] (TypeError(code: 0): strlen(): Argument #1 ($string) must be of type string, int given at /html/contao413/vendor/pdir/contao-survey/src/Resources/contao/forms/FormQuestionWidget.php:184)"} []

Other question types are working when the checkbox is ticked.

## Steps to reproduce
s. above

## Expected behavior
One can use "Fragentitel nicht anzeigen".

## Screenshots
![Bildschirmfoto 2023-09-12 um 12 18 25](https://github.com/pdir/contao-survey/assets/1969941/c7b34641-e3f4-4ca7-ac5a-71419d315d90)

## Environment

MacOS 13.4.1
PHP 8.2.5
Contao 4.13.30
Firefox 116.0.3

**Comment by fritzmg** [comment]
This has been fixed in https://github.com/pdir/contao-survey/commit/dcd296611e4b57a4f6b5882369f968df7addb380 (but hasn't been tagged in a release yet).
